name: Sync Api
on:
  push:
    paths:
      - 'staging/src/github.com/clusterpedia-io/api/*'
jobs:
  sync-api:
    name: Sync Api
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{ github.workspace }}/src/github.com/clusterpedia-io/clusterpedia
      API_REPO_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      MESSAGE: ${{ github.event.head_commit.message }}
      REFTYPE: ${{ github.ref_type }}
      TAGNAME: ${{ github.ref_name }}
      REF: ${{ github.ref }}
    defaults:
      run:
        working-directory: ${{ env.WORKSPACE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKSPACE }}
          ref: ${{ github.ref }}
          fetch-depth: 0
      - run: hack/sync-api-test.sh





